services:
  home-page:
    container_name: home-page
    image: kahosan/home-page
    user: 1000:1000
    environment:
      - TZ=Asia/Shanghai
      - HOME_TWITTER=https://twitter.com/kaho_suyf
      - HOME_BLOG=https://blog.kahosan.top/
      - HOME_HEADER_TITLE=Data Center
      - HOME_TITLE=NAS 数据中心
    volumes:
      - ./services.json:/app/services.json
    ports:
      - 3000:3000
